version: '3.7'

services:
  client:
    build:
      context: ./
      dockerfile: ./Dockerfile-client
    container_name: client
    volumes:
      - ./dist/frontend:/app/frontend/build
      - /app/node_modules

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
      - ./uploads:/var/www/public
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo
      - client
    command: sh -c "npm run build && npm run start" # ideális esetben dockerfileban buildeli le

  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
