tags:
- name: pictures
  description: pictures API

paths:
# [GET] pictures
  /pictures:
    get:
      tags:
      - pictures
      summary: Find All Pictures
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] pictures
    post:
      tags:
      - pictures
      summary: Add Picture
      parameters:
      - name: body
        in: body
        description: picture Data
        required: true
        schema:
          $ref: '#/definitions/pictures'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] pictures/id
  /pictures/{id}:
    get:
      tags:
      - pictures
      summary: Find Picture By Id
      parameters:
      - name: id
        in: path
        description: Picture Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] pictures/id
    put:
      tags:
      - pictures
      summary: Update Picture By Id
      parameters:
      - name: id
        in: path
        description: picture Id
        required: true
      - name: body
        in: body
        description: picture Data
        required: true
        schema:
          $ref: '#/definitions/pictures'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] pictures/id
    delete:
      tags:
      - pictures
      summary: Delete Picture By Id
      parameters:
      - name: id
        in: path
        description: picture Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  pictures:
    type: object
    required:
        - email
        - password
    properties:
      id:
        description: picture Id
      filename:
        type: string
        description: picture's filename
      uploaderIp:
        type: string
        description: picture's uploader's Ip address
      uploadDate:
        type: string
        description: picture's uploade datetime
      description:
        type: string
        description: picture's short description

schemes:
 - https
 - http
